### ISSUE TITLE
Nightly Updates

### ISSUE THREAD

**Issue by maxgrossman** [openaq/battuta#1]
@jflasher - could we just do a travis cron job for this? 
https://docs.travis-ci.com/user/cron-jobs/

**Comment by jflasher** [comment]
Yep, I think that's probably the easiest way to go

**Comment by maxgrossman** [comment]
Cool, I can make a branch and implement.

**Comment by maxgrossman** [comment]
@jflasher - hi! I have battuta's travis 90 % there. the next 10% is setting up the cron/push to github. 

I was going to mimic what I've done [here](https://github.com/MissingMaps/microsites/blob/master/.build_scripts/deploy.sh) except in the last line I'll just push to the master branch.

**Comment by maxgrossman** [comment]
handled by #2 and #3 so going to close.
